# Generated by Django 4.2.18 on 2025-06-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("arpas_augmentedreality", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_set",
                to="arpas_augmentedreality.scene",
            ),
        ),
    ]
