# Generated by Django 4.2.18 on 2025-06-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arpas_augmentedreality", "0002_alter_object_scene"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Object",
            new_name="ARObject",
        ),
        migrations.RenameField(
            model_name="variant",
            old_name="object",
            new_name="ar_object",
        ),
    ]
