# Generated by Django 4.2.18 on 2025-06-30 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("arpas_augmentedreality", "0003_auto_20250630_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arobject",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arobjects",
                to="arpas_augmentedreality.scene",
            ),
        ),
    ]
