# Generated by Django 4.2.18 on 2025-07-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("arpas_augmentedreality", "0004_alter_arobject_scene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenes",
                to="contenttypes.contenttype",
            ),
        ),
    ]
