# Generated by Django 4.2.18 on 2025-06-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "a4comments",
            "0014_rename_comment_content_type_object_pk_a4comments__content_ff606b_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ARComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="a4comments.comment",
                    ),
                ),
                ("fromAR", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("a4comments.comment",),
        ),
    ]
