name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Setup Postgres
        env:
          PGPASSWORD: postgres
          PGHOSTADDR: 127.0.0.1
        run: |
          psql -c 'create database django;' -U postgres
          psql -c 'create database django_test;' -U postgres
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache pip packages
        uses: actions/cache@v4
        env:
          cache-name: cache-pip-packages
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements/dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: check a4 hashes equal
        run: |
          ./scripts/a4-check.sh
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gdal-bin
          sudo apt install libsqlite3-mod-spatialite
          npm install
          npm run build
          pip install -r requirements/dev.txt
          pip install coveralls
      - name: Debug URL resolution
        run: |
          python manage.py shell -c "
          import sys
          from django.urls import resolve, get_resolver
          from django.contrib.contenttypes.models import ContentType
          
          print('\n=== DEBUGGING URL RESOLUTION ===', file=sys.stderr)
          
          try:
              # 1. Show all installed apps
              from django.conf import settings
              print('\nINSTALLED APPS:', settings.INSTALLED_APPS, file=sys.stderr)
              
              # 2. Show root URLconf
              print('\nROOT_URLCONF:', settings.ROOT_URLCONF, file=sys.stderr)
              
              # 3. Try importing your actual URLs module
              from your_project import urls  # Replace 'your_project' with your actual project name
              print('\nSuccessfully imported URLs module', file=sys.stderr)
              
              # 4. Print all URL patterns
              print('\nALL URL PATTERNS:', file=sys.stderr)
              for pattern in get_resolver().url_patterns:
                  print(pattern.pattern, file=sys.stderr)
              
              # 5. Test specific resolution
              ct_id = ContentType.objects.get_for_model('augmentedreality.Variant').id
              test_url = f'/api/contenttypes/{ct_id}/objects/1/arpas-comments/'
              print(f'\nTESTING URL: {test_url}', file=sys.stderr)
              
              match = resolve(test_url)
              print(f'\nSUCCESS! View: {match.func.__name__}', file=sys.stderr)
          except Exception as e:
              print(f'\nFAILED: {type(e).__name__}: {str(e)}', file=sys.stderr)
              raise
          "
      - name: Run Tests
        env:
          PGPASSWORD: postgres
          PGHOSTADDR: 127.0.0.1
        run: |
          python manage.py collectstatic > /dev/null
          DJANGO_SETTINGS_MODULE='adhocracy-plus.config.settings.travis' py.test --cov
          isort --diff -c adhocracy-plus tests
          python manage.py makemigrations --dry-run --check --noinput
          flake8 adhocracy-plus tests --exclude migrations,settings
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.COV }}
        run: |
          coveralls
      - name: Run Frontend Tests
        run: |
          npm test
          npm run lint
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          TRAVIS_SSH_SECRET: ${{ secrets.DEPLOY }}
        run: |
          ./scripts/deploy.sh
